ENH: Use override for destructors and = default where appropriate
KitwareMedical/ITKUltrasound pull request #170
Opened 2022-01-07 22:05 UTC by dzenanz

This only cleans up files which don't get removed in #161.

2022-01-10 23:06 UTC, dzenanz commented
Ping @tbirdso.

2022-01-10 23:06 UTC, dzenanz commented
@pranjalSahu could also review.

2022-01-11 00:08 UTC, tbirdso requested changes
One fix for CDash failures, otherwise LGTM

2022-01-11 00:08 UTC, tbirdso commented on include/itkBlockMatchingMultiResolutionIterationObserver.hxx
> +MultiResolutionIterationObserver<TMultiResolutionMethod>::~MultiResolutionIterationObserver() override
From [CDash](https://open.cdash.org/viewBuildError.php?buildid=7665861):

```
include/itkBlockMatchingMultiResolutionIterationObserver.hxx:51:95: error: virt-specifiers in 'MultiResolutionIterationObserver' not allowed outside a class definition
```

I don't think the `override` is need in the implementation here if it is included in the declaration in `itkBlockMatchingMultiResolutionIterationObserver.h `

2022-01-12 00:59 UTC, tbirdso reviewed
LGTM once CI issues are resolved

2022-01-12 00:59 UTC, tbirdso commented on include/itkFFTWCommonExtended.h
> +  ~ComplexToComplexProxy() override = default;
[CDash result](include/itkFFTWCommonExtended.h:49:28: error: only virtual member functions can be marked 'override')

Looks like `ComplexToComplexProxy` does not inherit from a superclass and should not use `override`

2022-01-12 18:06 UTC, PranjalSahu commented
LGTM

2022-01-12 18:26 UTC, merged